"use client";
import { useRef, useState, useTransition } from "react";
import { Button, Card } from "@/components/ui";
import { useToast } from "@/components/toaster";
import { allotAdmissionNumber } from "../actions";
type Student = { id: string; admission_number: string; mobile_number: string | null; section_id: string | null; profiles: { full_name: string } | null; classes: { name: string } | null; sections: { name: string } | null };
export function AdmissionAllotmentForm({ students, sections }: { students: Student[]; sections: { id: string; name: string; class_id: string }[] }) {
  const { push } = useToast(); const existing = new Set(students.map((s) => s.admission_number).filter(Boolean)); const suggested = (index: number) => { let n = `ADM${new Date().getFullYear()}${String(index + 1).padStart(4, "0")}`; let next = index + 1; while (existing.has(n)) n = `ADM${new Date().getFullYear()}${String(++next).padStart(4, "0")}`; return n; }; const initialValues = Object.fromEntries(students.map((s, index) => [s.id, s.admission_number || suggested(index)])); const [values, setValues] = useState(initialValues); const previousValues = useRef(initialValues); const [sectionValues, setSectionValues] = useState(Object.fromEntries(students.map((s) => [s.id, s.section_id ?? ""]))); const [selected, setSelected] = useState<string[]>([]); const [pending, startTransition] = useTransition();
  const update = (id: string, value: string) => { const next = value.toUpperCase().replace(/[^A-Z0-9-]/g, ""); if (next && Object.entries(previousValues.current).some(([other, current]) => other !== id && current === next)) { setValues((current) => ({ ...current, [id]: previousValues.current[id] ?? "" })); push("Duplicate admission number. Previous value restored.", "error"); } else { previousValues.current[id] = next; setValues((current) => ({ ...current, [id]: next })); } };
  const save = (ids: string[]) => { const nums = ids.map((id) => values[id]?.trim()); if (nums.some((n) => !n)) { push("Enter an admission number for every selected row.", "error"); return; } if (new Set(Object.values(values)).size !== Object.values(values).length) { push("Admission numbers cannot be repeated.", "error"); return; } startTransition(async () => { for (const id of ids) { const result = await allotAdmissionNumber(id, values[id], sectionValues[id]); if (result.error) { push(result.error, "error"); return; } } setSelected([]); push("Admission details saved"); }); };
  return <Card className="border-ink-100 p-0 shadow-sm"><div className="flex items-center justify-between border-b border-ink-100 bg-ink-50/70 px-4 py-2.5"><h2 className="font-display text-lg font-semibold text-ink-700">Admission numbers</h2><Button disabled={!selected.length || pending} onClick={() => save(selected)}>Save selected ({selected.length})</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-ink-100 text-left text-xs font-bold uppercase tracking-wide text-slate/50"><th className="px-4 py-3"><input type="checkbox" checked={selected.length === students.length && students.length > 0} onChange={(e) => setSelected(e.target.checked ? students.map((s) => s.id) : [])} /></th><th className="px-4 py-3">Student</th><th className="px-4 py-3">Class</th><th className="px-4 py-3">Section</th><th className="px-4 py-3">Admission number</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{students.map((s) => <tr key={s.id} className="border-b border-ink-100 last:border-0 hover:bg-gold-50/30"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(s.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, s.id] : selected.filter((id) => id !== s.id))} /></td><td className="px-4 py-3 font-semibold text-ink-700">{s.profiles?.full_name || "Unnamed student"}</td><td className="px-4 py-3 text-slate/70">{s.classes?.name || "—"}</td><td className="px-4 py-3"><select value={sectionValues[s.id] ?? ""} onChange={(e) => setSectionValues({ ...sectionValues, [s.id]: e.target.value })} className="min-h-10 w-40 rounded-lg border border-ink-100 bg-white px-3 py-2 text-sm"><option value="">Select section</option>{sections.filter((section) => !s.classes || section.class_id === (s.classes as any).id).map((section) => <option key={section.id} value={section.id}>{section.name}</option>)}</select></td><td className="px-4 py-3"><input value={values[s.id] ?? ""} onChange={(e) => update(s.id, e.target.value)} className="min-h-10 w-44 rounded-lg border border-ink-100 px-3 py-2 text-sm uppercase shadow-sm focus:border-gold-500 focus:outline-none focus:ring-4 focus:ring-gold-100" /></td><td className="px-4 py-3"><Button variant="ghost" disabled={pending} onClick={() => save([s.id])}>Save</Button></td></tr>)}</tbody></table>{!students.length && <p className="p-8 text-center text-sm text-slate/60">No student records found.</p>}</div></Card>;
}
