"use client";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui";
import { useToast } from "@/components/toaster";
import { bulkUpdateStudents } from "./actions";

type Option = { id: string; name: string; class_id?: string };
export function BulkStudentUpdate({ ids, classes, sections, sessions }: { ids: string[]; classes: Option[]; sections: Option[]; sessions: Option[] }) {
  const { push } = useToast(); const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition();
  const [selected, setSelected] = useState<string[]>([]); const [classId, setClassId] = useState(""); const [sectionId, setSectionId] = useState(""); const [sessionId, setSessionId] = useState("");
  const visibleSections = sections.filter((section) => section.class_id === classId);
  if (!open) return <Button variant="primary" disabled={!ids.length} onClick={() => setOpen(true)}>Bulk update</Button>;
  return <div className="fixed inset-0 z-30 grid place-items-center bg-ink-900/30 p-4"><div className="w-full max-w-lg rounded-lg bg-white p-6 shadow-xl"><h2 className="font-display text-xl text-ink-700">Bulk update students</h2><p className="mt-1 text-sm text-slate/60">Choose students and only the values you want to change.</p><div className="mt-4 max-h-32 overflow-auto rounded border border-ink-100 p-2 text-sm">{ids.map((id) => <label key={id} className="block py-1"><input type="checkbox" checked={selected.includes(id)} onChange={() => setSelected(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id])} /> <span className="ml-2">Student {id.slice(0, 8)}</span></label>)}</div><div className="mt-4 grid grid-cols-3 gap-3"><select className="rounded border border-ink-100 p-2 text-sm" value={classId} onChange={(e) => { setClassId(e.target.value); setSectionId(""); }}><option value="">Class (no change)</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="rounded border border-ink-100 p-2 text-sm" value={sectionId} onChange={(e) => setSectionId(e.target.value)} disabled={!classId}><option value="">Section (no change)</option>{visibleSections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="rounded border border-ink-100 p-2 text-sm" value={sessionId} onChange={(e) => setSessionId(e.target.value)}><option value="">Session (no change)</option>{sessions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={pending || !selected.length || (!classId && !sectionId && !sessionId)} onClick={() => startTransition(async () => { const { error, count } = await bulkUpdateStudents(selected, { class_id: classId || undefined, section_id: sectionId || undefined, session_id: sessionId || undefined }); if (error) push(error, "error"); else { push(`${count} student records updated`); setOpen(false); } })}>Update {selected.length} students</Button></div></div></div>;
}
