"use client";
import { useEffect, useRef, useState } from "react";

type Option = { id: string; name: string; label?: string }; type Pincode = { id: string; pincode: string; stateId: string; districtId: string; cityId: string | null; state: string; district: string; city: string | null; post_office_name: string | null };
function Combo({ label, value, placeholder, disabled, loading, options, onChange, onSearch, onSelect }: { label: string; value: string; placeholder: string; disabled?: boolean; loading?: boolean; options: Option[]; onChange: (value: string) => void; onSearch: () => void; onSelect: (option: Option) => void }) { const [open, setOpen] = useState(false); const [active, setActive] = useState(0); const ref = useRef<HTMLDivElement>(null); useEffect(() => { const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []); return <div className="relative" ref={ref}><label className="text-xs font-semibold text-slate-600">{label}</label><input value={value} disabled={disabled} placeholder={placeholder} onFocus={() => { setOpen(true); onSearch(); }} onChange={(event) => { onChange(event.target.value); setOpen(true); onSearch(); }} onKeyDown={(event) => { if (!open || !options.length) return; if (event.key === "ArrowDown") { event.preventDefault(); setActive((v) => Math.min(v + 1, options.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setActive((v) => Math.max(v - 1, 0)); } else if (event.key === "Enter") { event.preventDefault(); onSelect(options[active]); setOpen(false); } else if (event.key === "Escape") setOpen(false); }} className="mt-1 min-h-10 w-full rounded-xl border-2 border-slate-200 bg-white px-3 text-sm text-ink-700 outline-none focus:border-ink-700 disabled:bg-slate-100" />{open && !disabled && <div className="absolute left-0 right-0 top-full z-30 mt-1 max-h-56 overflow-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{loading ? <p className="px-3 py-2 text-xs text-slate-500">Loading...</p> : options.length ? options.map((option, index) => <button type="button" key={option.id} onMouseDown={(event) => event.preventDefault()} onClick={() => { onSelect(option); setOpen(false); }} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${index === active ? "bg-indigo-50 text-ink-700" : "hover:bg-slate-50"}`}>{option.label ?? option.name}</button>) : <p className="px-3 py-2 text-xs text-slate-500">No results found</p>}</div>}</div>; }

export function LocationSelector({ initialCountry = "India", initialState = "", initialDistrict = "", initialCity = "", initialPincode = "" }: { initialCountry?: string; initialState?: string; initialDistrict?: string; initialCity?: string; initialPincode?: string }) { const [state, setState] = useState(initialState); const [district, setDistrict] = useState(initialDistrict); const [city, setCity] = useState(initialCity); const [pincode, setPincode] = useState(initialPincode); const [stateId, setStateId] = useState(""); const [districtId, setDistrictId] = useState(""); const [cityId, setCityId] = useState(""); const [options, setOptions] = useState<Record<string, Option[]>>({ states: [], districts: [], cities: [], pincodes: [] }); const [loading, setLoading] = useState<string | null>(null);
  async function load(type: string, id = "", q = "") { setLoading(type); const response = await fetch(`/api/locations?type=${type}&id=${encodeURIComponent(id)}&q=${encodeURIComponent(q)}`, { cache: "no-store" }); const result = await response.json().catch(() => ({ data: [] })); setOptions((current) => ({ ...current, [type]: result.data ?? [] })); setLoading(null); }
  useEffect(() => { void load("states"); }, []);
  const chooseState = (option: Option) => { setState(option.name); setStateId(option.id); setDistrict(""); setDistrictId(""); setCity(""); setCityId(""); setPincode(""); setOptions((v) => ({ ...v, districts: [], cities: [], pincodes: [] })); void load("districts", option.id); };
  const chooseDistrict = (option: Option) => { setDistrict(option.name); setDistrictId(option.id); setCity(""); setCityId(""); setPincode(""); setOptions((v) => ({ ...v, cities: [], pincodes: [] })); void load("cities", option.id); };
  const chooseCity = (option: Option) => { setCity(option.name); setCityId(option.id); setPincode(""); void load("pincodes", option.id); };
  const choosePincode = (option: Option) => { const p = option as unknown as Pincode; setPincode(p.pincode); setState(p.state); setStateId(p.stateId); setDistrict(p.district); setDistrictId(p.districtId); setCity(p.city ?? ""); setCityId(p.cityId ?? ""); void load("districts", p.stateId); void load("cities", p.districtId); if (p.cityId) void load("pincodes", p.cityId, p.pincode); };
  return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="country" value={initialCountry} /><input type="hidden" name="state" value={state} /><input type="hidden" name="district" value={district} /><input type="hidden" name="city" value={city} /><input type="hidden" name="postal_code" value={pincode} /><Combo label="Pincode" value={pincode} placeholder="Search pincode" options={(options.pincodes as unknown as Pincode[]).map((p) => ({ ...p, name: p.pincode, label: `${p.pincode}${p.post_office_name ? ` — ${p.post_office_name}` : ""}` }))} loading={loading === "pincodes"} onChange={(value) => { setPincode(value); void load("pincodes", cityId, value); }} onSearch={() => undefined} onSelect={choosePincode} /><Combo label="Country" value={initialCountry} placeholder="India" disabled options={[]} onChange={() => undefined} onSearch={() => undefined} onSelect={() => undefined} /><Combo label="State" value={state} placeholder="Search state" options={options.states} loading={loading === "states"} onChange={setState} onSearch={() => void load("states", "", state)} onSelect={chooseState} /><Combo label="District" value={district} placeholder="Search district" disabled={!stateId} options={options.districts} loading={loading === "districts"} onChange={setDistrict} onSearch={() => void load("districts", stateId, district)} onSelect={chooseDistrict} /><Combo label="City / Locality" value={city} placeholder="Search city or locality" disabled={!districtId} options={options.cities} loading={loading === "cities"} onChange={setCity} onSearch={() => void load("cities", districtId, city)} onSelect={chooseCity} /></div>; }
