export const PERMISSIONS = {
  VIEW_STUDENTS: "view_students",
  MARK_ATTENDANCE: "mark_attendance",
  VIEW_FEE_STATUS: "view_fee_status",
  VIEW_REPORTS: "view_reports",
  MANAGE_SYSTEM_SETTINGS: "manage_system_settings",
  VIEW_STUDENT_DOCUMENTS: "view_student_documents",
  MANAGE_STUDENT_DOCUMENTS: "manage_student_documents",
  VIEW_STAFF_DOCUMENTS: "view_staff_documents",
  MANAGE_STAFF_DOCUMENTS: "manage_staff_documents",
  VIEW_SENSITIVE_DOCUMENTS: "view_sensitive_documents",
  MANAGE_SENSITIVE_DOCUMENTS: "manage_sensitive_documents",
  VIEW_DOCUMENT_AUDIT: "view_document_audit",
  LEAVING_STUDENTS_VIEW: "leaving_students.view",
  LEAVING_STUDENTS_CREATE: "leaving_students.create",
  LEAVING_STUDENTS_EDIT: "leaving_students.edit",
  LEAVING_STUDENTS_VERIFY: "leaving_students.verify",
  LEAVING_STUDENTS_APPROVE: "leaving_students.approve",
  LEAVING_STUDENTS_REJECT: "leaving_students.reject",
  LEAVING_STUDENTS_CANCEL: "leaving_students.cancel",
  LEAVING_STUDENTS_GENERATE_CERTIFICATE: "leaving_students.generate_certificate",
  LEAVING_STUDENTS_MANAGE_CLEARANCE: "leaving_students.manage_clearance",
  LEAVING_STUDENTS_VIEW_REPORTS: "leaving_students.view_reports",
} as const;
