import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requirePageAccess } from "@/lib/require-role";
import { createClient } from "@/lib/supabase/server";
import { Badge, Button, Card } from "@/components/ui";
import { SchoolLogoPreview } from "@/components/school-logo-preview";
import { getMasterDataContext } from "@/lib/security/master-data-context";

function Metric({ label, value, tone = "text-ink-700" }: { label: string; value: string | number; tone?: string }) { const accent = label === "Active wings" ? "border-l-emerald-500" : label === "Policies" ? "border-l-amber-500" : label === "Mapped classes" ? "border-l-indigo-500" : "border-l-ink-700"; const icon = label === "Active wings" ? "✓" : label === "Policies" ? "★" : label === "Mapped classes" ? "⌘" : "⌂"; const iconTone = label === "Active wings" ? "bg-emerald-50 text-emerald-600" : label === "Policies" ? "bg-amber-50 text-amber-500" : label === "Mapped classes" ? "bg-indigo-50 text-indigo-600" : "bg-indigo-50 text-ink-700"; const note = label === "Active wings" ? "Currently available" : label === "Policies" ? "Configured policies" : label === "Mapped classes" ? "Across all wings" : "Configured wings"; return <div className={`group relative flex min-h-[104px] gap-3 overflow-hidden rounded-2xl border border-slate-200 border-l-[5px] bg-white p-3.5 shadow-[0_6px_18px_rgba(30,42,74,0.08)] transition-all hover:-translate-y-0.5 hover:shadow-md sm:min-h-[116px] sm:p-4 ${accent}`}><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-base ${iconTone}`}>{icon}</div><div className="min-w-0 flex-1 pr-8"><p className="mb-1 truncate text-[11px] font-bold uppercase tracking-[0.14em] text-slate/65 sm:text-xs">{label}</p><p className={`text-2xl font-black leading-none sm:text-3xl ${tone}`}>{value}</p><p className="mt-2 truncate text-xs text-slate/70">{note}</p></div><div className={`absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full text-sm ${iconTone}`}>{icon}</div></div>; }
function DetailItem({ label, value }: { label: string; value: string | null | undefined }) { return <div className="min-w-0 rounded-xl border border-slate-200/80 bg-slate-50/70 px-3 py-2.5 text-left transition-colors hover:border-indigo-200 hover:bg-indigo-50/30"><p className="text-left text-[10px] font-bold uppercase tracking-[0.12em] text-slate/55">{label}</p><p className="mt-1 break-words text-left text-sm font-semibold text-ink-700">{value || "—"}</p></div>; }
function SectionHeading({ icon, title, subtitle, action }: { icon: string; title: string; subtitle: string; action?: React.ReactNode }) { const displayTitle = title === "School information" ? "Basic Information" : title === "Contact & location" || title === "Address details" ? "Contact Information" : title; return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-ink-600 bg-ink-700 px-4 py-2.5 text-left text-white sm:px-5"><div className="flex min-w-0 items-center gap-3 text-left"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white/10 text-sm font-bold text-white">{icon}</span><div className="min-w-0 text-left"><h2 className="font-display text-left text-base font-semibold leading-tight text-white sm:text-lg">{displayTitle}</h2><p className="mt-0.5 truncate text-left text-xs leading-tight text-white/70">{subtitle}</p></div></div>{action}</div>; }
const academicMonthName = (value: unknown) => { const month = Number(value); return Number.isInteger(month) && month >= 1 && month <= 12 ? new Date(2024, month - 1, 1).toLocaleString("en-US", { month: "long" }) : value ? String(value) : null; };
function AcademicConfiguration({ school }: { school: any }) { return <Card className="academic-configuration-card overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="▦" title="Academic Configuration" subtitle="Academic year and teaching preferences." /><div className="grid gap-4 p-4 sm:grid-cols-2 sm:p-5"><DetailItem label="Academic start month" value={academicMonthName(school.academic_start_month)} /><DetailItem label="Medium of instruction" value={school.medium_of_instruction} /></div></Card>; }
function CompleteContactInformation({ school }: { school: any }) { return <Card className="complete-contact-information-card overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="☎" title="Contact Information" subtitle="Contact details and communication preferences." /><div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3 sm:p-5"><DetailItem label="Primary Contact Person" value={school.contact_person} /><DetailItem label="Designation" value={school.contact_designation} /><DetailItem label="Mobile Number" value={school.phone} /><DetailItem label="Alternate Mobile" value={school.alternate_phone} /><DetailItem label="Email" value={school.email} /><DetailItem label="Website" value={school.website} /><DetailItem label="Address Line 1 *" value={school.address_line1} /><DetailItem label="Address Line 2" value={school.address_line2} /><DetailItem label="Pincode" value={school.postal_code} /><DetailItem label="Country" value={school.country} /><DetailItem label="State" value={school.state} /><DetailItem label="District" value={school.district} /><DetailItem label="City / Locality" value={school.city} /></div></Card>; }
function CompleteBasicInformation({ school, designTemplate, organization }: { school: any; designTemplate?: string | null; organization?: any }) { return <Card className="complete-basic-information-card overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="⌂" title="Basic Information" subtitle="School identity and registration details." /><div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3 sm:p-5"><DetailItem label="Organization" value={organization ? [organization.code, organization.name].filter(Boolean).join(" — ") : null} /><DetailItem label="School Name" value={school.name} /><DetailItem label="School Code" value={school.code} /><DetailItem label="Short Name" value={school.short_name} /><DetailItem label="School URL / Slug" value={school.slug} /><DetailItem label="School Type" value={school.school_type} /><DetailItem label="Board / Affiliation" value={school.board} /><DetailItem label="Affiliation Number" value={school.affiliation_number} /><DetailItem label="Established Year" value={school.established_year ? String(school.established_year) : null} /><DetailItem label="Design Template" value={designTemplate === "design-2" ? "Design 2" : "Design 1"} /><div className="sm:col-span-2 lg:col-span-3"><p className="text-left text-[10px] font-bold uppercase tracking-[0.12em] text-slate/55">School Logo</p>{school.logo_url ? <div className="mt-2"><SchoolLogoPreview src={String(school.logo_url)} alt={`${school.name} logo`} /></div> : <p className="mt-1 text-left text-sm font-semibold text-ink-700">—</p>}</div></div></Card>; }
function AdditionalSchoolInformation({ school }: { school: any }) { return <Card className="additional-school-information-card overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="⚙" title="System Settings" subtitle="Regional and display preferences." /><div className="grid gap-4 p-4 sm:grid-cols-3 sm:p-5"><DetailItem label="Timezone" value={school.timezone} /><DetailItem label="Currency" value={school.currency_code} /><DetailItem label="Date Format" value={school.date_format} /></div></Card>; }

export default async function SchoolDetailsPage({ params }: { params: { id: string } }) {
  await requirePageAccess("school_master");
  const context = await getMasterDataContext();
  if (context.loginScope === "school" && context.schoolId !== params.id) redirect(`/school-master/${context.schoolId}`);
  const supabase = await createClient();
  const { data: school } = await supabase.from("schools").select("*, organizations(id, code, name)").eq("id", params.id).maybeSingle();
  if (!school) notFound();
  const [{ data: wings }, { data: classes }, { data: website }] = await Promise.all([
    supabase.from("school_wings").select("id, wing_code, wing_name, description, is_active, wing_admission_policies(prefix, suffix, current_number, number_length, separator, include_academic_year, academic_year_format, is_active)").eq("school_id", params.id).order("display_order"),
    supabase.from("classes").select("id, wing_id").eq("school_id", params.id),
    supabase.from("school_websites").select("design_template").eq("school_id", params.id).maybeSingle(),
  ]);
  const organization = Array.isArray(school.organizations) ? school.organizations[0] : school.organizations;
  const wingRows = (wings ?? []).map((wing: any) => { const policy = Array.isArray(wing.wing_admission_policies) ? wing.wing_admission_policies[0] ?? null : wing.wing_admission_policies ?? null; const number = policy ? String((policy.current_number ?? 0) + 1).padStart(policy.number_length ?? 4, "0") : null; const startYear = new Date().getFullYear(); const endingYear = String((startYear + 1) % 100).padStart(2, "0"); let yearToken = 0; const academicYear = policy?.include_academic_year && policy.academic_year_format ? policy.academic_year_format.replace(/YYYY|YY/g, (token: string) => token === "YYYY" ? String(startYear + yearToken++) : endingYear) : null; return { ...wing, policy, classCount: (classes ?? []).filter((item: any) => item.wing_id === wing.id).length, preview: policy ? [policy.prefix, academicYear, number, policy.suffix].filter(Boolean).join(policy.separator ?? "/") : null }; });
  const activeWings = wingRows.filter((wing) => wing.is_active).length;
  const configuredPolicies = wingRows.filter((wing) => wing.policy?.is_active).length;
  const mappedClasses = (classes ?? []).filter((item: any) => item.wing_id).length;
  return <div className="school-details-page -mx-2 -mt-4 space-y-3 sm:-mx-3 sm:space-y-4 lg:-mx-4">
    <section className="overflow-hidden rounded-2xl border border-ink-100 border-l-4 border-l-gold-500 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3.5 sm:px-5"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-ink-700"><svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M3 21h18M5 21V8l7-4 7 4v13M9 21v-5h6v5M8 10h.01M12 10h.01M16 10h.01" strokeLinecap="round" strokeLinejoin="round" /></svg></div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate/60">School / Branch Master</p><h1 className="mt-0.5 truncate font-display text-xl font-semibold text-ink-700 sm:text-2xl">{school.name}</h1><p className="mt-0.5 truncate font-mono text-xs text-slate/60">{school.code}{organization?.name ? ` • ${organization.name}` : ""}</p></div></div><div className="flex flex-wrap gap-2">{context.loginScope !== "school" && <Link href="/school-master"><Button size="sm" variant="outline">← Back</Button></Link>}<Link href={`/school-master/new?id=${school.id}`}><Button size="sm">✎ Edit School</Button></Link></div></div><div className="grid grid-cols-2 gap-2 border-t border-ink-100 bg-slate-50/70 p-3 sm:grid-cols-4 sm:gap-3"><Metric label="Total wings" value={wingRows.length} /><Metric label="Active wings" value={activeWings} tone="text-emerald-700" /><Metric label="Mapped classes" value={mappedClasses} /><Metric label="Policies" value={`${configuredPolicies}/${wingRows.length}`} tone={configuredPolicies === wingRows.length ? "text-emerald-700" : "text-amber-700"} /></div></section>
    <div className="grid gap-3 lg:grid-cols-2 lg:gap-4"><Card className="overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="⌂" title="School information" subtitle="Identity and operating status." /><div className="grid gap-4 p-4 sm:grid-cols-2 sm:p-5"><DetailItem label="School name" value={school.name} /><DetailItem label="School code" value={school.code} /><DetailItem label="Organization" value={organization?.name} /><DetailItem label="Website slug" value={school.slug} /><DetailItem label="School type" value={school.school_type} /><DetailItem label="Board / affiliation" value={school.board} /><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate/55">Status</p><div className="mt-1"><Badge variant={school.is_active ? "default" : "destructive"}>{school.is_active ? "Active" : "Inactive"}</Badge></div></div></div></Card><Card className="overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="☎" title="Contact & location" subtitle="Contact details and registered address." /><div className="grid gap-4 p-4 sm:grid-cols-2 sm:p-5"><DetailItem label="Contact person" value={school.contact_person} /><DetailItem label="Designation" value={school.contact_designation} /><DetailItem label="Mobile" value={school.phone} /><DetailItem label="Email" value={school.email} /><div className="sm:col-span-2"><DetailItem label="Address" value={[school.address_line1, school.address_line2, school.city, school.state, school.country, school.postal_code].filter(Boolean).join(", ")} /></div></div></Card></div>
    <Card className="overflow-hidden rounded-2xl border border-ink-100 !p-0 shadow-sm"><SectionHeading icon="⌘" title="School wings" subtitle="Classes and wing-wise admission number policies." action={<Link href={`/wings?schoolId=${school.id}`}><Button size="sm">Manage Wings</Button></Link>} />{wingRows.length ? <div className="grid gap-3 p-3 sm:grid-cols-2 sm:p-4 lg:grid-cols-3">{wingRows.map((wing) => <article key={wing.id} className="rounded-xl border-2 border-indigo-200 bg-white p-3.5 shadow-sm transition-colors hover:border-indigo-400 hover:shadow-md"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="font-mono text-[10px] font-bold tracking-[0.12em] text-slate/55">{wing.wing_code}</p><h3 className="mt-1 truncate font-semibold text-ink-700">{wing.wing_name}</h3></div><Badge variant={wing.is_active ? "default" : "destructive"}>{wing.is_active ? "Active" : "Inactive"}</Badge></div><div className="mt-3 grid grid-cols-2 gap-2 border-t border-slate-100 pt-3 text-xs"><div className="rounded-lg bg-slate-50 px-2.5 py-2"><p className="text-slate/55">Classes</p><p className="mt-1 font-bold text-ink-700">{wing.classCount}</p></div><div className="rounded-lg bg-slate-50 px-2.5 py-2"><p className="text-slate/55">Policy</p><p className={`mt-1 font-bold ${wing.policy?.is_active ? "text-emerald-700" : "text-amber-700"}`}>{wing.policy?.is_active ? "Configured" : "Required"}</p></div></div>{wing.preview ? <div className="mt-3 rounded-lg border border-indigo-100 bg-indigo-50/50 px-3 py-2"><p className="text-[10px] font-bold uppercase tracking-wide text-indigo-700">Admission preview</p><p className="mt-1 truncate font-mono text-sm font-bold text-ink-700">{wing.preview}</p></div> : <p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700">Configure admission policy</p>}</article>)}</div> : <div className="px-5 py-10 text-center"><p className="font-semibold text-ink-700">No wings configured</p><p className="mt-1 text-sm text-slate/60">Create the first wing from Wing Master.</p><Link className="mt-3 inline-flex text-sm font-semibold text-ink-700 underline" href={`/wings?schoolId=${school.id}`}>Open Wing Master</Link></div>}</Card>
    <CompleteBasicInformation school={school} designTemplate={website?.design_template} organization={organization} />
    <CompleteContactInformation school={school} />
    <AdditionalSchoolInformation school={school} />
    <AcademicConfiguration school={school} />
  </div>;
}
