create table if not exists public.page_access_audit (
  id bigint generated by default as identity primary key,
  event_type text not null,
  organisation_id uuid not null references public.organizations(id) on delete cascade,
  page_id uuid not null references public.system_pages(id) on delete cascade,
  staff_user_id uuid references public.profiles(id) on delete set null,
  school_id uuid references public.schools(id) on delete set null,
  changed_by uuid references public.profiles(id) on delete set null,
  old_value boolean,
  new_value boolean,
  created_at timestamptz not null default now()
);
create index if not exists page_access_audit_org_idx on public.page_access_audit(organisation_id, created_at desc);
alter table public.page_access_audit enable row level security;
drop policy if exists page_access_audit_read_admin on public.page_access_audit;
create policy page_access_audit_read_admin on public.page_access_audit for select to authenticated using (public.is_super_admin() or public.has_organisation_access(organisation_id));

create or replace function public.validate_role_page_assignment()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not public.organisation_has_page(new.organisation_id, new.page_id) then raise exception 'Page is not enabled for this organisation'; end if;
  if exists (select 1 from public.staff_roles r where r.id = new.role_id and r.organization_id is not null and r.organization_id <> new.organisation_id) then raise exception 'Role does not belong to this organisation'; end if;
  return new;
end;
$$;
drop trigger if exists role_page_assignment_integrity on public.role_page_assignments;
create trigger role_page_assignment_integrity before insert or update on public.role_page_assignments for each row execute function public.validate_role_page_assignment();

create or replace function public.validate_staff_page_assignment()
returns trigger language plpgsql security definer set search_path = public as $$
declare target_org uuid; target_school uuid; target_type text;
begin
  select organization_id, school_id, user_type into target_org, target_school, target_type from public.profiles where id = new.staff_user_id and is_active;
  if target_org is null or target_org <> new.organisation_id then raise exception 'Staff member does not belong to this organisation'; end if;
  if target_type = 'SCHOOL_USER' and target_school is distinct from new.school_id then raise exception 'School staff access must use the assigned school'; end if;
  if not public.organisation_has_page(new.organisation_id, new.page_id) then raise exception 'Page is not enabled for this organisation'; end if;
  return new;
end;
$$;
drop trigger if exists staff_page_assignment_integrity on public.staff_page_access;
create trigger staff_page_assignment_integrity before insert or update on public.staff_page_access for each row execute function public.validate_staff_page_assignment();

create or replace function public.audit_organisation_page_access()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.page_access_audit(event_type, organisation_id, page_id, changed_by, old_value, new_value)
  values (case when coalesce(new.is_enabled, false) then 'ORGANISATION_PAGE_ENABLED' else 'ORGANISATION_PAGE_DISABLED' end, coalesce(new.organisation_id, old.organisation_id), coalesce(new.page_id, old.page_id), auth.uid(), old.is_enabled, new.is_enabled);
  return coalesce(new, old);
end;
$$;
drop trigger if exists audit_organisation_page_access_trigger on public.organisation_page_access;
create trigger audit_organisation_page_access_trigger after insert or update or delete on public.organisation_page_access for each row execute function public.audit_organisation_page_access();

create or replace function public.audit_staff_page_access()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.page_access_audit(event_type, organisation_id, page_id, staff_user_id, school_id, changed_by, old_value, new_value)
  values (case when tg_op = 'DELETE' or not coalesce(new.is_enabled, false) then 'STAFF_PAGE_REVOKED' else 'STAFF_PAGE_GRANTED' end, coalesce(new.organisation_id, old.organisation_id), coalesce(new.page_id, old.page_id), coalesce(new.staff_user_id, old.staff_user_id), coalesce(new.school_id, old.school_id), auth.uid(), old.is_enabled, new.is_enabled);
  return coalesce(new, old);
end;
$$;
drop trigger if exists audit_staff_page_access_trigger on public.staff_page_access;
create trigger audit_staff_page_access_trigger after insert or update or delete on public.staff_page_access for each row execute function public.audit_staff_page_access();

notify pgrst, 'reload schema';
