"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requirePageAccess } from "@/lib/require-role";
import { sanitizeStorageFileName, validateImageUpload } from "@/lib/security/uploads";
import { randomUUID } from "crypto";
import { isValidSchoolSlug } from "@/lib/website/tenant-path";

type State = { error: string | null; message?: string; id?: string };
async function guard() { await requirePageAccess("school_master"); }
function values(form: FormData) {
  const value = (key: string) => String(form.get(key) ?? "").trim() || null;
  return { organization_id: String(form.get("organization_id") ?? ""), name: String(form.get("name") ?? "").trim(), code: String(form.get("code") ?? "").trim().toUpperCase(), slug: String(form.get("slug") ?? "").trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-|-$/g, ""), design_template: (String(form.get("design_template") ?? "design-1") === "design-2" ? "design-2" : "design-1") as "design-2" | "design-1", is_active: form.get("is_active") !== "false", short_name: value("short_name"), logo_url: value("logo_url"), school_type: value("school_type"), board: value("board"), affiliation_number: value("affiliation_number"), established_year: value("established_year") ? Number(value("established_year")) : null, contact_person: value("contact_person"), contact_designation: value("contact_designation"), phone: value("phone"), alternate_phone: value("alternate_phone"), email: value("email"), website: value("website"), address_line1: value("address_line1"), address_line2: value("address_line2"), country: value("country"), state: value("state"), district: value("district"), city: value("city"), postal_code: value("postal_code"), academic_start_month: value("academic_start_month") ? Number(value("academic_start_month")) : null, medium_of_instruction: value("medium_of_instruction"), timezone: value("timezone"), date_format: value("date_format"), currency_code: value("currency_code") };
}
function logoFile(form: FormData) { const file = form.get("logo_file"); return file instanceof File && file.size > 0 ? file : null; }
function valid(input: ReturnType<typeof values>) {
  const email = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email ?? "");
  const phone = /^[6-9]\d{9}$/.test((input.phone ?? "").replace(/\D/g, ""));
  const alternatePhone = !input.alternate_phone || /^[6-9]\d{9}$/.test(input.alternate_phone.replace(/\D/g, ""));
  const postalCode = /^[a-zA-Z0-9 -]{3,10}$/.test(input.postal_code ?? "");
  const website = !input.website || (() => { try { const url = new URL(input.website); return url.protocol === "http:" || url.protocol === "https:"; } catch { return false; } })();
  const currentYear = new Date().getFullYear();
  const establishedYear = input.established_year === null || (Number.isInteger(input.established_year) && input.established_year >= 1800 && input.established_year <= currentYear);
  const academicMonth = input.academic_start_month === null || (Number.isInteger(input.academic_start_month) && input.academic_start_month >= 1 && input.academic_start_month <= 12);
  const safeText = (value: string | null, max: number) => !value || (value.length <= max && !/[\u0000-\u001f\u007f]/.test(value));
  return Boolean(input.organization_id && input.name.length >= 2 && safeText(input.name, 120) && /^[A-Z0-9_-]{2,30}$/.test(input.code) && isValidSchoolSlug(input.slug) && input.school_type && input.contact_person && safeText(input.contact_person, 120) && phone && alternatePhone && email && input.address_line1 && input.country && input.state && input.city && postalCode && website && establishedYear && academicMonth);
}
function validationError(input: ReturnType<typeof values>) {
  if (!input.organization_id) return "Organization is required.";
  if (input.name.length < 2 || !safeSchoolText(input.name, 120)) return "School Name must contain at least 2 valid characters.";
  if (!/^[A-Z0-9_-]{2,30}$/.test(input.code)) return "School Code must be 2–30 characters using letters, numbers, underscores, or hyphens.";
  if (!isValidSchoolSlug(input.slug)) return "School URL / Slug is required and must use lowercase letters, numbers, and hyphens.";
  if (!input.school_type) return "School Type is required.";
  if (!input.contact_person || !safeSchoolText(input.contact_person, 120)) return "Primary Contact Person is required.";
  if (!phoneIsValid(input.phone)) return "Mobile Number must be 10 digits and start with 6, 7, 8, or 9.";
  if (input.alternate_phone && !phoneIsValid(input.alternate_phone)) return "Alternate Mobile must be 10 digits and start with 6, 7, 8, or 9.";
  if (!emailIsValid(input.email)) return "Email must be a valid email address.";
  if (!input.address_line1) return "Address Line 1 is required.";
  if (!input.country) return "Country is required.";
  if (!input.state) return "State is required.";
  if (!input.city) return "City is required.";
  if (!/^[a-zA-Z0-9 -]{3,10}$/.test(input.postal_code ?? "")) return "Postal Code must be 3 to 10 letters or numbers.";
  return "Please review the highlighted school details.";
}
const safeSchoolText = (value: string | null, max: number) => Boolean(value && value.length <= max && !/[\u0000-\u001f\u007f]/.test(value));
const phoneIsValid = (value: string | null) => /^[6-9]\d{9}$/.test((value ?? "").replace(/\D/g, ""));
const emailIsValid = (value: string | null) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value ?? "");
const isMissingAcademicColumnError = (error: { message?: string } | null) => Boolean(error?.message && /academic_start_month|medium_of_instruction|timezone|date_format|currency_code/.test(error.message));
function withoutAcademicSettings<T extends Record<string, unknown>>(payload: T) { const { academic_start_month: _academicStartMonth, medium_of_instruction: _medium, timezone: _timezone, date_format: _dateFormat, currency_code: _currency, ...legacyPayload } = payload; return legacyPayload; }
async function saveWebsiteDesign(admin: ReturnType<typeof createAdminClient>, schoolId: string, organizationId: string, designTemplate: "design-1" | "design-2") {
  return admin.from("school_websites").upsert({ organization_id: organizationId, school_id: schoolId, design_template: designTemplate, status: "active" }, { onConflict: "school_id" });
}
export async function createSchool(_state: State, form: FormData): Promise<State> { await guard(); const input = values(form); if (!valid(input)) return { error: validationError(input) }; const file = logoFile(form); const fileError = file ? validateImageUpload(file) : null; if (fileError) return { error: fileError }; const supabase = await createClient(); const { data: org } = await supabase.from("organizations").select("id").eq("id", input.organization_id).eq("is_active", true).maybeSingle(); if (!org) return { error: "Organization is invalid or inactive." }; const admin = createAdminClient(); let uploadedPath: string | null = null; let logoUrl = input.logo_url; if (file) { uploadedPath = `schools/${randomUUID()}-${sanitizeStorageFileName(file.name)}`; const { error: uploadError } = await admin.storage.from("school-logos").upload(uploadedPath, file, { contentType: file.type, upsert: false }); if (uploadError) return { error: uploadError.message }; logoUrl = admin.storage.from("school-logos").getPublicUrl(uploadedPath).data.publicUrl; } const { design_template, ...schoolInput } = input; const schoolPayload = { ...schoolInput, logo_url: logoUrl }; let { data, error } = await supabase.from("schools").insert(schoolPayload).select("id").single(); if (error && isMissingAcademicColumnError(error)) ({ data, error } = await supabase.from("schools").insert(withoutAcademicSettings(schoolPayload)).select("id").single()); if (error) { if (uploadedPath) await admin.storage.from("school-logos").remove([uploadedPath]); return { error: error.code === "23505" ? "School Code or School URL / Slug already exists." : error.message }; } if (!data) { if (uploadedPath) await admin.storage.from("school-logos").remove([uploadedPath]); return { error: "School could not be created." }; } const { error: websiteError } = await saveWebsiteDesign(admin, data.id, input.organization_id, design_template); if (websiteError) return { error: `School created, but its website design could not be saved: ${websiteError.message}` }; revalidatePath("/school-master"); revalidatePath(`/organization-master/${input.organization_id}`); return { error: null, message: "School created successfully.", id: data.id }; }
export async function updateSchool(id: string, _state: State, form: FormData): Promise<State> { await guard(); const input = values(form); if (!id) return { error: "School ID is required." }; if (!valid(input)) return { error: validationError(input) }; const file = logoFile(form); const fileError = file ? validateImageUpload(file) : null; if (fileError) return { error: fileError }; const supabase = await createClient(); const { data: existing } = await supabase.from("schools").select("organization_id,logo_url").eq("id", id).maybeSingle(); if (!existing) return { error: "School was not found." }; const { data: org } = await supabase.from("organizations").select("id").eq("id", input.organization_id).maybeSingle(); if (!org) return { error: "Organization does not exist." }; const admin = createAdminClient(); let uploadedPath: string | null = null; let logoUrl = input.logo_url || existing.logo_url; if (file) { uploadedPath = `schools/${randomUUID()}-${sanitizeStorageFileName(file.name)}`; const { error: uploadError } = await admin.storage.from("school-logos").upload(uploadedPath, file, { contentType: file.type, upsert: false }); if (uploadError) return { error: uploadError.message }; logoUrl = admin.storage.from("school-logos").getPublicUrl(uploadedPath).data.publicUrl; } const { organization_id: _organizationId, design_template: _designTemplate, ...editable } = input; const editablePayload = { ...editable, logo_url: logoUrl, updated_at: new Date().toISOString() }; let { error } = await supabase.from("schools").update(editablePayload).eq("id", id); if (error && isMissingAcademicColumnError(error)) ({ error } = await supabase.from("schools").update(withoutAcademicSettings(editablePayload)).eq("id", id)); if (error) { if (uploadedPath) await admin.storage.from("school-logos").remove([uploadedPath]); return { error: error.code === "23505" ? "School Code or School URL / Slug already exists." : error.message }; } const { error: websiteError } = await saveWebsiteDesign(admin, id, input.organization_id, input.design_template); if (websiteError) return { error: `School updated, but its website design could not be saved: ${websiteError.message}` }; revalidatePath("/school-master"); revalidatePath(`/school-master/${id}/edit`); revalidatePath(`/organization-master/${existing.organization_id}`); return { error: null, message: "School updated successfully." }; }
export async function toggleSchool(id: string, isActive: boolean): Promise<void> { await guard(); const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("schools").update({ is_active: isActive, inactive_reason: isActive ? null : "Status changed by administrator", updated_at: new Date().toISOString() }).eq("id", id); if (!error) { await supabase.from("school_status_history").insert({ school_id: id, status: isActive ? "active" : "inactive", reason: "Status changed by administrator", created_by: user?.id ?? null }); revalidatePath("/school-master"); } }

export async function deactivateSchool(id: string, _state: State, form: FormData): Promise<State> { await guard(); const reason = String(form.get("reason") ?? "").trim(); if (reason.length < 3) return { error: "Please provide a reason for deactivation." }; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("schools").update({ is_active: false, inactive_reason: reason, updated_at: new Date().toISOString() }).eq("id", id); if (error) return { error: error.message }; await supabase.from("school_status_history").insert({ school_id: id, status: "inactive", reason, created_by: user?.id ?? null }); revalidatePath("/school-master"); revalidatePath(`/school-master/${id}`); return { error: null, message: `School deactivated: ${reason}` }; }

export async function activateSchool(id: string, _state: State, form: FormData): Promise<State> { await guard(); const reason = String(form.get("reason") ?? "").trim(); if (reason.length < 3) return { error: "Please provide an activation reason." }; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); const { error } = await supabase.from("schools").update({ is_active: true, inactive_reason: null, updated_at: new Date().toISOString() }).eq("id", id); if (error) return { error: error.message }; await supabase.from("school_status_history").insert({ school_id: id, status: "active", reason, created_by: user?.id ?? null }); revalidatePath("/school-master"); revalidatePath(`/school-master/${id}`); return { error: null, message: `School activated: ${reason}` }; }
