import Link from "next/link";
import { Badge, Button } from "@/components/ui";
import { StatusHistoryModal, type StatusHistoryItem } from "@/components/status-history-modal";
import { SchoolStatusModal } from "./school-status-modal";

type School = { id: string; name: string; code: string; slug: string; school_type: string | null; board: string | null; contact_person: string | null; city: string | null; is_active: boolean; inactive_reason?: string | null; short_name?: string | null };

export function SchoolTable({ schools, historyBySchool, wingCounts }: { schools: School[]; historyBySchool: Map<string, StatusHistoryItem[]>; wingCounts: Map<string, number> }) {
  return <div className="hidden overflow-x-auto px-1 pb-2 sm:px-2 md:block"><table className="w-full min-w-[1140px] border-collapse text-left text-sm"><thead><tr className="border-b-2 border-ink-200 bg-ink-700 text-[10px] uppercase tracking-[0.14em] text-white"><th className="px-2 py-2.5 sm:px-3">School</th><th className="px-2 py-2.5 sm:px-3">Code</th><th className="px-2 py-2.5 sm:px-3">Wings</th><th className="px-2 py-2.5 sm:px-3">Type</th><th className="px-2 py-2.5 sm:px-3">Board</th><th className="px-2 py-2.5 sm:px-3">Contact</th><th className="px-2 py-2.5 sm:px-3">Location</th><th className="px-2 py-2.5 sm:px-3">Status</th><th className="px-2 py-2.5 sm:px-3">Remark</th><th className="px-2 py-2.5 sm:px-3">Actions</th></tr></thead><tbody>{schools.map((school) => <tr key={school.id} className="border-b border-ink-100 odd:bg-white even:bg-ink-50/50 transition-colors hover:bg-gold-50/60 last:border-0"><td className="px-2 py-2.5 sm:px-3"><Link href={`/school-master/${school.id}`} className="font-semibold text-ink-700 hover:text-gold-700">{school.name}</Link><p className="mt-1 text-xs text-slate/55">{school.short_name ?? `/${school.slug}`}</p></td><td className="px-2 py-2.5 font-mono text-xs font-bold tracking-wide text-slate/75 sm:px-3">{school.code}</td><td className="px-2 py-2.5 sm:px-3"><Link href={`/wings?schoolId=${school.id}`} className="font-semibold text-ink-700 underline decoration-ink-200 underline-offset-2 hover:text-gold-700">{wingCounts.get(school.id) ?? 0}</Link></td><td className="px-2 py-2.5 sm:px-3">{school.school_type ?? "—"}</td><td className="px-2 py-2.5 sm:px-3">{school.board ?? "—"}</td><td className="px-2 py-2.5 sm:px-3">{school.contact_person ?? "—"}</td><td className="px-2 py-2.5 sm:px-3">{school.city ?? "—"}</td><td className="px-2 py-2.5 sm:px-3"><Badge variant={school.is_active ? "default" : "destructive"}>{school.is_active ? "Active" : "Inactive"}</Badge></td><td className="px-2 py-2.5 sm:px-3"><StatusHistoryModal title={school.name} items={historyBySchool.get(school.id) ?? []} /></td><td className="px-2 py-2.5 sm:px-3"><div className="flex flex-nowrap gap-1.5"><Link href={`/school-master/${school.id}`}><Button size="sm" variant="outline">↗ View</Button></Link><Link href={`/school-master/new?id=${school.id}`}><Button size="sm" variant="outline">✎ Edit</Button></Link><SchoolStatusModal id={school.id} name={school.name} activate={!school.is_active} /></div></td></tr>)}</tbody></table></div>;
}
