"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useFormState, useFormStatus } from "react-dom";
import { Button, Card, Input, Label } from "@/components/ui";
import { useToast } from "@/components/toaster";
import { createSchool, updateSchool } from "./actions";

type Organization = { id: string; name: string; code: string };
type SchoolValues = { organization_id: string; name: string; code: string; slug: string; is_active: boolean; [key: string]: string | number | boolean | null };
const sections = [
  { title: "Basic Information", icon: "⌂", fields: [["name", "School Name", true], ["code", "School Code", true], ["short_name", "Short Name"], ["school_type", "School Type", true], ["board", "Board / Affiliation"], ["affiliation_number", "Affiliation Number"], ["established_year", "Established Year"], ["logo_file", "School Logo"]] },
  { title: "Contact Information", icon: "♙", fields: [["contact_person", "Primary Contact Person", true], ["contact_designation", "Designation"], ["phone", "Mobile Number", true], ["alternate_phone", "Alternate Mobile"], ["email", "Email", true], ["website", "Website"]] },
  { title: "Address", icon: "⌖", fields: [["address_line1", "Address Line 1", true], ["address_line2", "Address Line 2"], ["country", "Country", true], ["state", "State", true], ["district", "District"], ["city", "City", true], ["postal_code", "PIN / Postal Code", true]] },
  { title: "Academic Configuration", icon: "▦", fields: [["academic_start_month", "Academic Start Month"], ["medium_of_instruction", "Medium of Instruction"], ["lowest_class", "Lowest Class"], ["highest_class", "Highest Class"]] },
  { title: "System Settings", icon: "⚙", fields: [["timezone", "Timezone"], ["currency_code", "Currency"], ["date_format", "Date Format"], ["default_language", "Default Language"], ["student_id_prefix", "Student ID Prefix"], ["admission_prefix", "Admission Number Prefix"]] },
] as const;

function SaveButton({ edit }: { edit: boolean }) { const { pending } = useFormStatus(); return <Button disabled={pending} className="min-h-11 w-full rounded-xl px-6 shadow-sm sm:w-auto">{pending ? "Saving…" : edit ? "Save changes" : "Create school"}</Button>; }
function fieldType(name: string) { return name === "email" ? "email" : name === "website" ? "url" : name === "established_year" || name === "academic_start_month" ? "number" : "text"; }

export function SchoolForm({ organizations, initial, id, fixedOrganizationId }: { organizations: Organization[]; initial?: SchoolValues; id?: string; fixedOrganizationId?: string }) {
  const edit = Boolean(id); const { push } = useToast(); const router = useRouter(); const action = edit ? updateSchool.bind(null, id!) : createSchool; const [state, formAction] = useFormState(action, { error: null as string | null }); const [clientError, setClientError] = useState<string | null>(null);
  const [organizationId, setOrganizationId] = useState(String(fixedOrganizationId ?? initial?.organization_id ?? organizations[0]?.id ?? ""));
  useEffect(() => { if (state.message) { push(state.message); if (!edit && organizationId) router.push(`/organization-master/${organizationId}`); } }, [state.message, push, edit, organizationId, router]);
  const inputClass = "mt-1 min-h-10 w-full rounded-xl border-2 border-slate-200 bg-white px-3 text-sm text-ink-700 shadow-sm outline-none transition focus:border-ink-700 focus:ring-4 focus:ring-indigo-100";
  const validateBeforeSubmit = (event: FormEvent<HTMLFormElement>) => { const form = event.currentTarget; const required = Array.from(form.querySelectorAll<HTMLInputElement | HTMLSelectElement>("[required]")); const empty = required.find((field) => !field.value.trim()); if (empty) { event.preventDefault(); setClientError(`${empty.getAttribute("aria-label") || empty.name || "This field"} is required.`); empty.focus(); return; } const email = form.elements.namedItem("email") as HTMLInputElement | null; if (email && !email.checkValidity()) { event.preventDefault(); setClientError("Enter a valid email address."); email.focus(); return; } const website = form.elements.namedItem("website") as HTMLInputElement | null; if (website?.value && !website.checkValidity()) { event.preventDefault(); setClientError("Enter a valid website URL."); website.focus(); return; } const phone = form.elements.namedItem("phone") as HTMLInputElement | null; if (phone && phone.value.replace(/\D/g, "").length !== 10) { event.preventDefault(); setClientError("Mobile Number must contain exactly 10 digits."); phone.focus(); return; } setClientError(null); };
  return <form action={formAction} onSubmit={validateBeforeSubmit} noValidate className="pb-20 sm:pb-0"><div className="space-y-4">
    <Card className="rounded-2xl border border-ink-100 border-l-4 border-l-[#24345f] !p-3 shadow-sm sm:!p-4">
      {!edit && fixedOrganizationId ? <div><Label htmlFor="organization_display">Organization</Label><div id="organization_display" className="mt-1.5 flex min-h-11 items-center rounded-xl border-2 border-[#24345f]/20 bg-blue-50/70 px-3 text-sm font-semibold text-ink-700">{organizations.find((org) => org.id === fixedOrganizationId)?.code} — {organizations.find((org) => org.id === fixedOrganizationId)?.name}</div><input type="hidden" name="organization_id" value={fixedOrganizationId} /></div> : !edit && <div><Label htmlFor="organization_id">Organization</Label><select id="organization_id" name="organization_id" required value={organizationId} onChange={(e) => setOrganizationId(e.target.value)} className={inputClass}><option value="">Select organization</option>{organizations.map((org) => <option key={org.id} value={org.id}>{org.code} — {org.name}</option>)}</select></div>}
      {edit && <input type="hidden" name="organization_id" value={organizationId} />}
      {(clientError || state.error) && <p className="mt-4 rounded-xl border border-danger/20 bg-danger/5 px-4 py-3 text-sm text-danger">{clientError || state.error}</p>}
    </Card>
    {sections.map((section) => <Card key={section.title} className="rounded-2xl border border-ink-100 !p-3 shadow-sm sm:!p-4"><div className="flex items-center gap-2.5 rounded-xl border border-[#24345f] bg-[#24345f] px-3 py-2 text-white"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white text-[#24345f] shadow-sm">{section.icon}</div><div><h3 className="font-display text-base font-semibold text-white">{section.title}</h3><p className="text-[11px] text-white/70">Enter the {section.title.toLowerCase()} details.</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{section.fields.map(([name, label, required]) => <div key={name} className={name === "logo_file" ? "sm:col-span-2 lg:col-span-3" : ""}><Label htmlFor={name}>{label}{required ? " *" : ""}</Label>{name === "logo_file" ? <><Input id={name} name={name} type="file" accept="image/jpeg,image/png,image/webp" className={`${inputClass} file:mr-3 file:rounded-lg file:border-0 file:bg-[#24345f] file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-white`} />{initial?.logo_url && <input type="hidden" name="logo_url" value={String(initial.logo_url)} />}</> : <Input id={name} name={name} required={Boolean(required)} type={fieldType(name)} defaultValue={String(initial?.[name] ?? "")} className={inputClass} />}</div>)}</div></Card>)}
    <Card className="rounded-2xl border border-ink-100 !p-3 shadow-sm sm:!p-4"><div className="flex items-center gap-2.5 rounded-xl border border-[#24345f] bg-[#24345f] px-3 py-2 text-white"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white text-[#24345f] shadow-sm">✓</div><div><h3 className="font-display text-base font-semibold text-white">Status</h3><p className="text-[11px] text-white/70">Set the current availability of this school.</p></div></div><div className="mt-3 max-w-sm"><Label htmlFor="is_active">Status</Label><select id="is_active" name="is_active" defaultValue={initial?.is_active === false ? "false" : "true"} className={inputClass}><option value="true">Active</option><option value="false">Inactive</option></select></div></Card>
    <div className="sticky bottom-0 z-10 -mx-4 flex justify-end border-t border-ink-100 bg-white/95 px-4 py-3 backdrop-blur sm:static sm:mx-0 sm:border-0 sm:bg-transparent sm:px-0 sm:py-0"><SaveButton edit={edit} /></div>
  </div></form>;
}
