"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useFormState, useFormStatus } from "react-dom";
import { Button, Card, Input, Label } from "@/components/ui";
import { useToast } from "@/components/toaster";
import { createSchool, updateSchool } from "./actions";
import { LocationSelector } from "@/components/location-selector";

type Organization = { id: string; name: string; code: string };
type SchoolValues = { organization_id: string; name: string; code: string; slug: string; design_template?: "design-1" | "design-2"; is_active: boolean; [key: string]: string | number | boolean | null | undefined };
const sections = [
  { title: "Basic Information", icon: "⌂", fields: [["name", "School Name", true], ["code", "School Code", true], ["short_name", "Short Name"], ["school_type", "School Type", true], ["board", "Board / Affiliation"], ["affiliation_number", "Affiliation Number"], ["established_year", "Established Year"], ["logo_file", "School Logo"]] },
  { title: "Contact Information", icon: "♙", fields: [["contact_person", "Primary Contact Person", true], ["contact_designation", "Designation"], ["phone", "Mobile Number", true], ["alternate_phone", "Alternate Mobile"], ["email", "Email", true], ["website", "Website"]] },
 
  { title: "Academic Configuration", icon: "▦", fields: [["academic_start_month", "Academic Start Month"], ["medium_of_instruction", "Medium of Instruction"]] },
  { title: "System Settings", icon: "⚙", fields: [["timezone", "Timezone"], ["currency_code", "Currency"], ["date_format", "Date Format"]] },
] as const;

function SaveButton({ edit }: { edit: boolean }) { const { pending } = useFormStatus(); return <Button disabled={pending} className="min-h-11 w-full rounded-xl px-6 shadow-sm sm:w-auto">{pending ? "Saving…" : edit ? "Save changes" : "Create school"}</Button>; }
function fieldType(name: string) { return name === "email" ? "email" : name === "website" ? "url" : name === "established_year" ? "number" : "text"; }
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

export function SchoolForm({ organizations, initial, id, fixedOrganizationId }: { organizations: Organization[]; initial?: SchoolValues; id?: string; fixedOrganizationId?: string }) {
  const edit = Boolean(id); const { push } = useToast(); const router = useRouter(); const action = edit ? updateSchool.bind(null, id!) : createSchool; const [state, formAction] = useFormState(action, { error: null as string | null }); const [clientError, setClientError] = useState<string | null>(null); const [feedback, setFeedback] = useState<{ type: "error" | "success"; message: string } | null>(null);
  const [organizationId, setOrganizationId] = useState(String(fixedOrganizationId ?? initial?.organization_id ?? organizations[0]?.id ?? ""));
  const [logoPreview, setLogoPreview] = useState<string | null>(initial?.logo_url ? String(initial.logo_url) : null);
  const [logoModalOpen, setLogoModalOpen] = useState(false);
  useEffect(() => () => { if (logoPreview?.startsWith("blob:")) URL.revokeObjectURL(logoPreview); }, [logoPreview]);
  useEffect(() => { if (clientError) { setFeedback({ type: "error", message: clientError }); window.dispatchEvent(new CustomEvent("app-feedback", { detail: { type: "error", message: clientError } })); } }, [clientError]);
  useEffect(() => { if (state.error) { setFeedback({ type: "error", message: state.error }); window.dispatchEvent(new CustomEvent("app-feedback", { detail: { type: "error", message: state.error } })); } if (state.message) { setFeedback({ type: "success", message: state.message }); window.dispatchEvent(new CustomEvent("app-feedback", { detail: { type: "success", message: state.message } })); if (!edit && organizationId) setTimeout(() => router.push(`/organization-master/${organizationId}`), 1200); } }, [state.error, state.message, edit, organizationId, router]);
  const inputClass = "mt-1 min-h-10 w-full rounded-xl border-2 border-slate-200 bg-white px-3 text-sm text-ink-700 shadow-sm outline-none transition focus:border-ink-700 focus:ring-4 focus:ring-indigo-100";
  const validateBeforeSubmit = (event: FormEvent<HTMLFormElement>) => { const form = event.currentTarget; const required = Array.from(form.querySelectorAll<HTMLInputElement | HTMLSelectElement>("[required]")); const empty = required.find((field) => !field.value.trim()); if (empty) { event.preventDefault(); setClientError(`${empty.getAttribute("aria-label") || empty.name || "This field"} is required.`); empty.focus(); return; } const email = form.elements.namedItem("email") as HTMLInputElement | null; if (email && !email.checkValidity()) { event.preventDefault(); setClientError("Enter a valid email address."); email.focus(); return; } const website = form.elements.namedItem("website") as HTMLInputElement | null; if (website?.value && !website.checkValidity()) { event.preventDefault(); setClientError("Enter a valid website URL."); website.focus(); return; } const phone = form.elements.namedItem("phone") as HTMLInputElement | null; if (phone && !/^[6-9]\d{9}$/.test(phone.value.replace(/\D/g, ""))) { event.preventDefault(); setClientError("Mobile Number must be 10 digits and start with 6, 7, 8, or 9."); phone.focus(); return; } const alternatePhone = form.elements.namedItem("alternate_phone") as HTMLInputElement | null; if (alternatePhone?.value && !/^[6-9]\d{9}$/.test(alternatePhone.value.replace(/\D/g, ""))) { event.preventDefault(); setClientError("Alternate Mobile must be 10 digits and start with 6, 7, 8, or 9."); alternatePhone.focus(); return; } const year = form.elements.namedItem("established_year") as HTMLInputElement | null; if (year?.value && (!/^\d{4}$/.test(year.value) || Number(year.value) < 1800 || Number(year.value) > new Date().getFullYear())) { event.preventDefault(); setClientError("Enter a valid established year."); year.focus(); return; } const month = form.elements.namedItem("academic_start_month") as HTMLInputElement | null; if (month?.value && (Number(month.value) < 1 || Number(month.value) > 12)) { event.preventDefault(); setClientError("Academic start month must be between 1 and 12."); month.focus(); return; } const postal = form.elements.namedItem("postal_code") as HTMLInputElement | null; if (postal && !/^[a-zA-Z0-9 -]{3,10}$/.test(postal.value.trim())) { event.preventDefault(); setClientError("Enter a valid postal code."); postal.focus(); return; } setClientError(null); };
  return <form action={formAction} onSubmit={validateBeforeSubmit} noValidate className="pb-20 sm:pb-0"><div className="space-y-4">
    <Card className="rounded-2xl border border-ink-100 !p-3 shadow-sm sm:!p-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="slug">School URL / Slug *</Label><Input id="slug" name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="abc-school" defaultValue={String(initial?.slug ?? "")} className={inputClass} /><p className="mt-1 text-xs text-slate/60">Lowercase letters, numbers, and hyphens only.</p></div><div><Label htmlFor="design_template">Design Template</Label><select id="design_template" name="design_template" defaultValue={String(initial?.design_template ?? "design-1")} className={inputClass}><option value="design-1">Design 1</option><option value="design-2">Design 2</option></select></div></div></Card>
    <Card className="rounded-2xl border border-ink-100 border-l-4 border-l-[#24345f] !p-3 shadow-sm sm:!p-4">
      {!edit && fixedOrganizationId ? <div><Label htmlFor="organization_display">Organization</Label><div id="organization_display" className="mt-1.5 flex min-h-11 items-center rounded-xl border-2 border-[#24345f]/20 bg-blue-50/70 px-3 text-sm font-semibold text-ink-700">{organizations.find((org) => org.id === fixedOrganizationId)?.code} — {organizations.find((org) => org.id === fixedOrganizationId)?.name}</div><input type="hidden" name="organization_id" value={fixedOrganizationId} /></div> : !edit && <div><Label htmlFor="organization_id">Organization</Label><select id="organization_id" name="organization_id" required value={organizationId} onChange={(e) => setOrganizationId(e.target.value)} className={inputClass}><option value="">Select organization</option>{organizations.map((org) => <option key={org.id} value={org.id}>{org.code} — {org.name}</option>)}</select></div>}
      {edit && <input type="hidden" name="organization_id" value={organizationId} />}
      {(clientError || state.error) && <p className="mt-4 rounded-xl border border-danger/20 bg-danger/5 px-4 py-3 text-sm text-danger">{clientError || state.error}</p>}
    </Card>
    <Card className="rounded-2xl border border-ink-100 !p-3 shadow-sm sm:!p-4"><div className="mb-3 flex items-center gap-2.5 rounded-xl border border-[#24345f] bg-[#24345f] px-3 py-2 text-white"><div className="grid h-8 w-8 place-items-center rounded-lg bg-white text-[#24345f]">⌖</div><div><h3 className="font-display text-base font-semibold">Location</h3><p className="text-[11px] text-white/70">Enter the address and select the school location.</p></div></div><div className="mb-3 grid gap-3 sm:grid-cols-2"><div><Label htmlFor="address_line1">Address Line 1 *</Label><Input id="address_line1" name="address_line1" required defaultValue={String(initial?.address_line1 ?? "")} className={inputClass} /></div><div><Label htmlFor="address_line2">Address Line 2</Label><Input id="address_line2" name="address_line2" defaultValue={String(initial?.address_line2 ?? "")} className={inputClass} /></div></div><LocationSelector initialCountry={String(initial?.country ?? "India")} initialState={String(initial?.state ?? "")} initialDistrict={String(initial?.district ?? "")} initialCity={String(initial?.city ?? "")} initialPincode={String(initial?.postal_code ?? "")} /></Card>
    {sections.map((section) => <Card key={section.title} className="rounded-2xl border border-ink-100 !p-3 shadow-sm sm:!p-4"><div className="flex items-center gap-2.5 rounded-xl border border-[#24345f] bg-[#24345f] px-3 py-2 text-white"><div className="grid h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-white text-[#24345f] shadow-sm">{section.icon}</div><div><h3 className="font-display text-base font-semibold text-white">{section.title}</h3><p className="text-[11px] text-white/70">Enter the {section.title.toLowerCase()} details.</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{section.fields.map(([name, label, required]) => <div key={name} className={name === "logo_file" ? "sm:col-span-2 lg:col-span-3" : ""}><Label htmlFor={name}>{label}{required ? " *" : ""}</Label>{name === "logo_file" ? <div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><Input id={name} name={name} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file = event.target.files?.[0]; setLogoPreview(file ? URL.createObjectURL(file) : (initial?.logo_url ? String(initial.logo_url) : null)); }} className={`${inputClass} file:mr-3 file:rounded-lg file:border-0 file:bg-[#24345f] file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-white`} />{initial?.logo_url && <input type="hidden" name="logo_url" value={String(initial.logo_url)} />}</div>{logoPreview ? <div className="flex shrink-0 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-2"><button type="button" onClick={() => setLogoModalOpen(true)} className="rounded-lg focus:outline-none focus:ring-4 focus:ring-indigo-200" aria-label="Open logo preview"><img src={logoPreview} alt="School logo preview" className="h-16 w-16 rounded-lg border border-slate-200 bg-white object-contain p-1" /></button><div className="hidden sm:block"><p className="text-sm font-semibold text-ink-700">Logo preview</p><p className="text-xs text-slate/60">Click image to enlarge</p></div></div> : <p className="shrink-0 text-xs text-slate/60">Choose a JPG, PNG, or WEBP image.</p>}</div> : name === "academic_start_month" ? <select id={name} name={name} defaultValue={String(initial?.[name] ?? "")} className={inputClass}><option value="">Select month</option>{months.map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</select> : <Input id={name} name={name} required={Boolean(required)} type={fieldType(name)} defaultValue={String(initial?.[name] ?? "")} className={inputClass} />}</div>)}</div></Card>)}
    <Card className="rounded-2xl border border-ink-100 !p-3 shadow-sm sm:!p-4"><div className="flex items-center gap-2.5 rounded-xl border border-[#24345f] bg-[#24345f] px-3 py-2 text-white"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white text-[#24345f] shadow-sm">✓</div><div><h3 className="font-display text-base font-semibold text-white">Status</h3><p className="text-[11px] text-white/70">Set the current availability of this school.</p></div></div><div className="mt-3 max-w-sm"><Label htmlFor="is_active">Status</Label><select id="is_active" name="is_active" defaultValue={initial?.is_active === false ? "false" : "true"} className={inputClass}><option value="true">Active</option><option value="false">Inactive</option></select></div></Card>
    <div className="sticky bottom-0 z-10 -mx-4 flex justify-end border-t border-ink-100 bg-white/95 px-4 py-3 backdrop-blur sm:static sm:mx-0 sm:border-0 sm:bg-transparent sm:px-0 sm:py-0"><SaveButton edit={edit} /></div>
  </div>{logoModalOpen && logoPreview && <div role="dialog" aria-modal="true" aria-label="School logo preview" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/75 p-4" onClick={() => setLogoModalOpen(false)}><div className="relative max-h-[90vh] max-w-[90vw] rounded-2xl bg-white p-3 shadow-2xl" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => setLogoModalOpen(false)} className="absolute -right-3 -top-3 grid h-9 w-9 place-items-center rounded-full bg-slate-950 text-lg text-white shadow-lg" aria-label="Close logo preview">×</button><img src={logoPreview} alt="School logo enlarged preview" className="max-h-[82vh] max-w-[82vw] rounded-xl object-contain" /></div></div>}</form>;
}
