"use client";
import { useEffect, useState } from "react";
import { useFormState, useFormStatus } from "react-dom";
import { Button, Card, Input, Label } from "@/components/ui";
import { useToast } from "@/components/toaster";
import { createOrganization, updateOrganization } from "./actions";

function SaveButton({ edit }: { edit: boolean }) { const { pending } = useFormStatus(); return <Button disabled={pending}>{pending ? "Saving…" : edit ? "Save changes" : "Add organization"}</Button>; }
export function OrganizationForm({ initial, id, embedded = false, onSuccess, hideStatus = false }: { initial?: { name: string; code: string; is_active: boolean }; id?: string; embedded?: boolean; onSuccess?: () => void; hideStatus?: boolean }) {
  const edit = Boolean(id); const { push } = useToast(); const action = edit ? updateOrganization.bind(null, id!) : createOrganization;
  const [state, formAction] = useFormState(action, { error: null as string | null });
  const [name, setName] = useState(initial?.name ?? ""); const [code, setCode] = useState(initial?.code ?? ""); const [active, setActive] = useState(initial?.is_active ?? true); const [loginIdentifier, setLoginIdentifier] = useState("");
  useEffect(() => { if (state.message) { push(state.message); if (!edit) { setName(""); setCode(""); setActive(true); setLoginIdentifier(""); } onSuccess?.(); } }, [state.message, push, onSuccess, edit]);
  const fieldClass = "mt-1.5 min-h-11 border-2 border-slate-300 bg-white shadow-sm focus:border-ink-700 focus:ring-4 focus:ring-slate-300/80 focus:outline-none";
  const content = <>{!embedded && <div className="flex items-center gap-2.5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-50 text-lg text-ink-700">◎</span><div><h2 className="font-display text-lg font-semibold text-ink-700">{edit ? "Edit organization" : "Organization details"}</h2><p className="text-xs text-slate/60">Set the organization identity and availability.</p></div></div>}{state.error && <p className="mt-4 rounded-xl border border-danger/20 bg-danger/5 px-4 py-3 text-sm text-danger">{state.error}</p>}{state.message && <p className="mt-1 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm text-emerald-800">{state.message}</p>}<div className={`${embedded ? "mt-3" : "mt-5"} grid gap-4 sm:grid-cols-2`}><div className="sm:col-span-2"><Label htmlFor="name">Organization name</Label><Input id="name" name="name" required value={name} onChange={e => setName(e.target.value)} placeholder="e.g. ABC Education Group" className={fieldClass} /></div><div><Label htmlFor="code">Organization code</Label><Input id="code" name="code" required value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="e.g. ABC001" className={fieldClass} /></div>{!edit && <div><Label htmlFor="login_identifier">Default login user ID</Label><Input id="login_identifier" name="login_identifier" required type="text" inputMode="text" autoComplete="username" value={loginIdentifier} onChange={e => setLoginIdentifier(e.target.value)} placeholder="Email ID or mobile number" className={fieldClass} /><p className="mt-1 text-xs text-slate/60">This will be used to sign in to the default organization admin account.</p></div>}{hideStatus && <input type="hidden" name="is_active" value={active ? "true" : "false"} />}{!hideStatus && <div className={edit ? "sm:col-span-2" : ""}><Label htmlFor="is_active">Status</Label><select id="is_active" name="is_active" value={active ? "true" : "false"} onChange={e => setActive(e.target.value === "true")} className={`${fieldClass} w-full rounded-xl px-3 text-sm text-ink-700`}><option value="true">Active</option><option value="false">Inactive</option></select></div>}</div><div className="mt-6 flex justify-end"><SaveButton edit={edit} /></div></>;
  return <form action={formAction}>{embedded ? <div>{content}</div> : <Card className="max-w-2xl">{content}</Card>}</form>;
}
